### ISSUE TITLE
UIMongolTableView有个bug

### ISSUE THREAD

**Issue by kerasking** [suragch/MongolAppDevelopment-iOS#1]
suragch，您好，我测试您代码的时候发现了UIMongolTableView存在的bug，在TableViewDemoVC 这个文件里面的

```
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        print("You selected cell #\(indexPath.row)!")

        let tmp = UIViewController()
        self.navigationController?.pushViewController(tmp, animated:false )

    }
```

下面是新加的测试代码，

```
let tmp = UIViewController()
self.navigationController?.pushViewController(tmp, animated:false )
```

然后点击返回的时候列表显示不正常了。

![img_0381](https://cloud.githubusercontent.com/assets/998105/12649282/e4b0b580-c618-11e5-9d4c-9981b813d72d.jpg)
![img_0383](https://cloud.githubusercontent.com/assets/998105/12649290/efc654c0-c618-11e5-81d2-1da6ef56f47b.jpg)

**Comment by suragch** [comment]
修复了，在IB里的TableViewDemoVC取消勾选中的“Adjust Scroll View Insets“。

![screen shot 2016-01-29 at 10 36 50 am](https://cloud.githubusercontent.com/assets/10300220/12665883/27bd21f8-c676-11e5-90e2-25c9729902df.png)
- http://stackoverflow.com/questions/18880341/why-is-there-extra-padding-at-the-top-of-my-uitableview-with-style-uitableviewst
- http://stackoverflow.com/questions/18906919/remove-empty-space-before-cells-in-uitableview
